### ISSUE TITLE
Using an own timeseries

### ISSUE THREAD

**Issue by lv-bakker** [TimeSynth/TimeSynth#14]
Hi,

I've got my own timeseries to which I want to add noise using the noise generator.
Is there a way to integrate my own timeseries as if it was generated by the package? 
Within "timeseries.py", I've already circumvented the need for vectorization (which gave an attribute error) by ignoring the if and elif statements.

However, when running, it says that my dataframe has no attribute "sample_next". I understand why this is, but I was wondering if there is an easy way to do something like "sample_next" without using that specific function. If that is achieved, everything should work.

**Comment by 1Reinier** [comment]
I would just sample some noise and add it to your time series with numpy directly.
