### ISSUE TITLE
symengine==0.4.0 forestalls Python 3.8 usage

### ISSUE THREAD

**Issue by swight-prc** [TimeSynth/TimeSynth#19]
Is there something about symengine>0.4.0 that breaks TimeSynth? Because this requirement keeps your library from being used in Python 3.8

I like your library, but I don't want to stay stuck in 3.7 if I can avoid it.

**Comment by swight-prc** [comment]
FWIW, I cloned the repo and changed the dependency, and (at least for my purposes) everything still worked fine. I didn't run a comprehensive test.

**Comment by 1Reinier** [comment]
Good to hear—do you have a fork or PR somewhere? Then I can have Travis test it and merge it in.

**Comment by swight-prc** [comment]
No, but I can push one when I get home from work today.

**Comment by swight-prc** [comment]
All I did was change the dependency to `symengine>=0.4.0`, then install Timesynth and test my app (which uses like 3 things from ts). Pull request incoming, but heads up, it's not much.
