### ISSUE TITLE
jitcdde needs == 0.32

### ISSUE THREAD

**Issue by ricpruss** [TimeSynth/TimeSynth#4]
Current git version of jitcdde does not have provide_advanced_symbols, so the 
import timesynth as ts fails.

The commit that makes the change in jitcdde is here:
https://github.com/neurophysik/jitcdde/commit/7dc8e85e1057ac9ffe8bb279fe83d9aa4e442454#diff-3f8fb500f61af0428394d41b462c2632

The workaround is simply:
```
pip install jitcdde==0.32
```

**Comment by 1Reinier** [comment]
Can you submit a pull request?

**Comment by ricpruss** [comment]
Summited: https://github.com/TimeSynth/TimeSynth/pull/6

**Comment by 1Reinier** [comment]
Will evaluate and merge it tonight (ET). Thanks!

**Comment by 1Reinier** [comment]
Merged your PR
