### ISSUE TITLE
Add this library to pip or conda

### ISSUE THREAD

**Issue by 1kastner** [TimeSynth/TimeSynth#5]
Hi there,

first of all thanks for sharing this project! It is a great help. I would love to add this via pip or conda instead of the classic installation procedure. Do you have plans of doing that? In case of interest we could also share the work. When looking at e.g. https://packaging.python.org/tutorials/packaging-projects/ it seems rather easy.

Best wishes

**Comment by 1Reinier** [comment]
Will take a look!

**Comment by 1Reinier** [comment]
Will do this tonight

**Comment by peterdcotton** [comment]
Did this happen? I'm happy to play with this.

**Comment by 1Reinier** [comment]
Sorry forgot about it. Wanna give it a shot and add it to pip?

**Comment by cpoptic** [comment]
Has TimeSynth been added to pip or conda?  Trying to avoid having to git clone the library just to install.

**Comment by 1Reinier** [comment]
yes

**Comment by 1Reinier** [comment]
Let me know if this is working for you. Put it on there not long ago

**Comment by 1Reinier** [comment]
I may need to get the newest version on there as on some machines it does not find the main module name. Weird.
