### ISSUE TITLE
time_sampler = ts.TimeSampler(stop_time=20) 

### ISSUE THREAD

**Issue by cpoptic** [TimeSynth/TimeSynth#9]
From the example:

> import TimeSynth as ts
> time_sampler = ts.TimeSampler(stop_time=20)

gives error:
AttributeError: module 'TimeSynth' has no attribute 'TimeSampler'

instead it should be:

> import TimeSynth.timesynth as ts
> from TimeSynth.timesynth import timesampler
> time_sampler = ts.TimeSampler(stop_time=20)

The above works.  Just need one level down.
Yep, this is on Python 3.6

**Comment by 1Reinier** [comment]
The build is passing. Are you using Python 3.5 or higher?
